# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

on:
  push: {}
  schedule:
  - cron: '47 4 * * *'

jobs:
  test:
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        python-version:
        - '3.7'
        - '3.8'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Install system dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install \
          gtk+3 \
          pygobject3
    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install \
          gir1.2-gtk-3.0 \
          libgirepository1.0-dev
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      env:
        # Brew on macOS outputs a message to set these environment variables.
        LDFLAGS: '-L/usr/local/opt/libffi/lib'
        PKG_CONFIG_PATH: '/usr/local/opt/libffi/lib/pkgconfig'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # TODO: Add a linter.
    - name: Check formatting
      run: |
        pip install yapf
        yapf --parallel --diff --recursive .
    - name: Cache pytype analysis
      uses: actions/cache@v1
      with:
        path: .pytype
        key: pytype-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/*.py') }}
        restore-keys: |
          pytype-${{ runner.os }}-${{ matrix.python-version }}-
    - name: Run pytype
      # TODO(https://github.com/google/pytype/issues/440): Remove this
      # condition.
      if: matrix.python-version != '3.8'
      run: |
        pip install pytype
        pytype
    - name: Test (xvfb graphics)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install xvfb
        pip install pytest pytest-cov
        xvfb-run pytest --cov=. --cov-branch --cov-report=term-missing
    - name: Test (native graphics)
      if: runner.os != 'Linux'
      run: |
        pip install pytest pytest-cov
        pytest --cov=. --cov-branch --cov-report=term-missing
